import mongoose from 'mongoose';

/**
 * GoalDecisionLog
 *
 * Purpose:
 *  - Persist the *decision-making process* for a Goal, not just the final plan.
 *  - Each document represents one AI-assisted step within the 4-Stage workflow
 *    (Definition, Strategy, Product, Simulation).
 *  - Enables "Transparent Co-piloting" by keeping a full audit trail of:
 *      - What the AI asked for (dynamic form schema)
 *      - What the user provided (user_input)
 *      - What the AI recommended (ai_decision)
 *      - How this step influenced the final Goal (committed_to_goal)
 */

// Sub-schema: AI decision payload for a single step
const AiDecisionSchema = new mongoose.Schema({
  recommendation: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
    description: 'Structured recommendation from AI (e.g., suggested risk level, updated target/due_date, product candidates).',
  },
  rationale: {
    type: String,
    maxlength: 4000,
    description: 'Natural language explanation shown in the Copilot panel for this step.',
  },
  plausible: {
    type: Boolean,
    default: true,
    description: 'Whether the AI believes this configuration is feasible under current constraints.',
  },
}, { _id: false });

const GoalDecisionLogSchema = new mongoose.Schema({
  // --- Core references ---
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  goal_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Goal',
    required: false,
    index: true,
    // May be null for early-stage sessions before a Goal document is created.
  },

  // Session / Orchestrator context
  session_id: {
    type: String,
    required: true,
    index: true,
    description: 'Identifier for a continuous orchestration / chat session.',
  },

  // Which stage of the 4-Stage workflow this step belongs to
  stage: {
    type: String,
    required: true,
    enum: ['definition', 'strategy', 'product', 'simulation'],
  },

  // Optional: more granular sequencing inside a stage
  step_index: {
    type: Number,
    default: 0,
    description: 'Monotonic counter within a session+stage to keep steps ordered.',
  },

  // Which agent handled this step (helps debugging multi-agent orchestration)
  agent_role: {
    type: String,
    enum: ['orchestrator', 'intake', 'analyst', 'advisor', 'market', 'simulation'],
    description: 'Logical role of the agent that produced this decision.',
  },
  llm_model: {
    type: String,
    description: 'Model identifier used for this step (e.g., claude-3.5-sonnet).',
  },

  // Snapshot of goal parameters at the time of this decision
  goal_snapshot: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
    description: 'Flattened view of goal parameters at this step (target_amount, due_date, riskTolerance, funding_mix, contribution_plan, etc.).',
  },

  // Dynamic form that AI asked the user to fill (field configs, labels, validation rules, etc.)
  form_schema: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
    description: 'Dynamic form definition generated by AI and rendered on the frontend for this step.',
  },

  // User payload submitted from the frontend for this form
  user_input: {
    type: mongoose.Schema.Types.Mixed,
    default: {},
    description: 'Raw user input corresponding to form_schema for this decision step.',
  },

  // AI decision derived from user_input + existing GoalContext
  ai_decision: {
    type: AiDecisionSchema,
    default: () => ({}),
  },

  // How the user responded to this particular AI decision
  user_action: {
    type: String,
    enum: ['accepted', 'modified', 'rejected', 'skipped', null],
    default: null,
    description: 'High-level label of how the user acted on this recommendation in the UI.',
  },

  // Whether this step was the one that updated the main Goal document
  committed_to_goal: {
    type: Boolean,
    default: false,
    description: 'True if this decision snapshot was used to update Goal fields (e.g., riskTolerance, funding_mix).',
  },

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
});

// Helpful compound index for analytics: per-goal chronological decision history
GoalDecisionLogSchema.index({ goal_id: 1, created_at: 1 });

export default mongoose.model('GoalDecisionLog', GoalDecisionLogSchema);


